### ISSUE TITLE
Values of CurseForgeModLinks may be null

### ISSUE THREAD

**Issue by pskfyi** [Smiley43210/curseforge-api#2]
The documented API of [`CurseForgeModLinks`](https://github.com/Smiley43210/curseforge-api/blob/main/src/v1/Types.ts#L457-L462) indicates the values are always `string`, but they are actually `null` rather than `""` when not provided.

**Comment by minimusubi** [comment]
Sorry about that. Typings are generated directly from https://docs.curseforge.com/, and it's listed as `string` there (https://docs.curseforge.com/#tocS_ModLinks). They do sometimes list null as a type ([example](https://docs.curseforge.com/#tocS_Category)), but apparently its not accurate. I may have to simply settle on making all properties of received data optional.

**Comment by minimusubi** [comment]
Upon revisiting this issue, it seems that the API is inconsistent, even within individual endpoints. For example, the Get Mod endpoint returns both empty strings as well as nulls. Looks like `wikiUrl` is always a string, but `issuesUrl` and `sourceUrl` can be null. Using one of the most recently updated mods as an example, I see:
```js
{
  websiteUrl: 'https://www.curseforge.com/minecraft/mc-mods/flois-addon',
  wikiUrl: '',
  issuesUrl: null,
  sourceUrl: null
}
```
